config/routes.rb
Rails.application.routes.draw do
 

  get '/checktodayreport' => 'application#checktodayreport'
  get '/checklastdayreport' => 'application#checklastdayreport'
  
  
  get '/threesixties/checkreport' => 'threesixties#checkreport'
  get '/sogous/checkreport' => 'sogous#checkreport'
  get '/shenmas/checkreport' => 'shenmas#checkreport'
  get '/baidu/checkreport' => 'baidus#checkreport'

  get '/click' => 'application#click'
  get '/event' => 'application#event'

  get '/g_normal_conversion' => 'application#g_normal_conversion'

  get '/ctriprevenuereport' => 'application#ctriprevenuereport'

  get '/watchdog' => 'application#watchdog'
  get '/watchdograndom' => 'application#watchdograndom'
  get '/watchdogreset' => 'application#watchdogreset'
  get '/watchdogreport' => 'application#watchdogreport'
  
  get '/cleanwatchdogfile' => 'application#cleanwatchdogfile'
  
  

  get '/getmissingeventfile' => 'application#getmissingeventfile'
  get '/cleaneventfile' => 'application#cleaneventfile'
  get '/exporteventfile' => 'application#exporteventfile'
  get '/geteventfile' => 'application#geteventfile'
  
  get '/getmissingclickfile' => 'application#getmissingclickfile'
  get '/cleanclickfile' => 'application#cleanclickfile'
  get '/exportclickfile' => 'application#exportclickfile'
  get '/getclickfile' => 'application#getclickfile'

  get '/checktag' => 'application#checktag'

  get '/checkkeywordtag' => 'application#checkkeywordtag'
  get '/checkadtag' => 'application#checkadtag'
  
  get '/cleanlogfile' => 'application#cleanlogfile'
  get '/cleanbulkfile' => 'application#cleanbulkfile'
  get '/cleanadvancedsearchfile' => 'application#cleanadvancedsearchfile'

  post '/bulkjob' => 'application#bulkjob'
  get '/runbulkjob' => 'application#runbulkjob'
  
  
  
  get '/shenmas/test' => 'shenmas#test'
  get '/shenmas/report' => 'shenmas#report'
  
  get '/shenmas/resetreport' => 'shenmas#resetreport'
  get '/shenmas/resetnetwork' => 'shenmas#resetnetwork'
  get '/shenmas/resetdlfile' => 'shenmas#resetdlfile'
  
  get '/shenmas/avgposition' => 'shenmas#avgposition'
  
  get '/shenmas/report_tmp' => 'shenmas#report_tmp'
  
  get '/shenmas/dlaccfile' => 'shenmas#dlaccfile'
  get '/shenmas/campaign' => 'shenmas#campaign'
  get '/shenmas/adgroup' => 'shenmas#adgroup'
  get '/shenmas/ad' => 'shenmas#ad'
  get '/shenmas/keyword' => 'shenmas#keyword'
  
  get '/shenmas/apicampaign' => 'shenmas#apicampaign'
  get '/shenmas/apiadgroup' => 'shenmas#apiadgroup'
  
  get '/shenmas/updateaccount' => 'shenmas#updateaccount'
  

  get '/sogous/campaign' => 'sogous#campaign'
  get '/sogous/adgroup' => 'sogous#adgroup'
  get '/sogous/ad' => 'sogous#ad'
  get '/sogous/keyword' => 'sogous#keyword'
  
  get '/sogous/apiadgroup' => 'sogous#apiadgroup'
  get '/sogous/apicampaign' => 'sogous#apicampaign'
  
  get '/sogous/resetreport' => 'sogous#resetreport'
  get '/sogous/threemonthsreport' => 'sogous#threemonthsreport'
  get '/sogous/report' => 'sogous#report'
  get '/sogous/avgposition' => 'sogous#avgposition'
  get '/sogous/avgposition_upper' => 'sogous#avgpositionupper'
  get '/sogous/resetdlfile' => 'sogous#resetdlfile'
  get '/sogous/resetnetwork' => 'sogous#resetnetwork'
  
  get '/sogous/updateaccount' => 'sogous#updateaccount'
  get '/sogous/dlaccfile' => 'sogous#dlaccfile'
  
  
  get '/test' => 'sogous#test'
  get '/test2' => 'threesixties#test'
  get '/test3' => 'baidus#test'
  get '/test4' => 'shenmas#test'

  
  get '/threesixties/campaign' => 'threesixties#campaign'
  get '/threesixties/adgroup' => 'threesixties#adgroup'
  get '/threesixties/ad' => 'threesixties#ad'
  get '/threesixties/keyword' => 'threesixties#keyword'
  
  get '/threesixties/campaignandadgroup' => 'threesixties#campaignandadgroup'
  get '/threesixties/adandkeyword' => 'threesixties#adandkeyword'
  
  get '/threesixties/apicampaign' => 'threesixties#apicampaign'
  get '/threesixties/apiadgroup' => 'threesixties#apiadgroup'
  
  get '/threesixties/resetreport' => 'threesixties#resetreport'
  get '/threesixties/threemonthsreport' => 'threesixties#threemonthsreport'
  get '/threesixties/report' => 'threesixties#report'
  get '/threesixties/report_upper' => 'threesixties#report_upper'
  get '/threesixties/resetdlfile' => 'threesixties#resetdlfile'
  get '/threesixties/resetnetwork' => 'threesixties#resetnetwork'
  
  get '/threesixties/updateaccount' => 'threesixties#updateaccount'
  get '/threesixties/dlaccfile' => 'threesixties#dlaccfile'
  
  get '/threemonthsevent' => 'application#threemonthsevent'
  get '/threemonthsclicks' => 'application#threemonthsclicks'
  get '/g_conversion' => 'application#g_conversion'
  get '/g_revenue' => 'application#g_revenue'
  
  get '/advancedsearchjob' => 'application#advancedsearchjob'
  get '/checkquote' => 'application#checkquote'
  
  
  get '/baidu/apicampaign' => 'baidus#apicampaign'
  get '/baidu/apiadgroup' => 'baidus#apiadgroup'
  
  get '/baidu/resetreport' => 'baidus#resetreport'
  get '/baidu/report' => 'baidus#report'
  get '/baidu/avgposition' => 'baidus#avgposition'
  
  
  
  get '/baidu/dlaccfile' => 'baidus#dlaccfile'
  
  get '/baidu/updateaccount' => 'baidus#updateaccount'
  
  get '/baidu/campaign' => 'baidus#campaign'
  get '/baidu/adgroup' => 'baidus#adgroup'
  get '/baidu/ad' => 'baidus#ad'
  get '/baidu/keyword' => 'baidus#keyword'
  
  get '/baidu/resetdlfile' => 'baidus#resetdlfile'
  get '/baidu/resetnetwork' => 'baidus#resetnetwork'
  
  
  resources :sogous
  resources :threesixties
  resources :baidus
  resources :shenmas

  get '*unmatched_route' => 'application#not_found'
  

  

end

app/models/sogou.rb
class Sogou < ActiveRecord::Base
end

app/controllers/sogous_controller.rb
class SogousController < ApplicationController
  # before_action :set_sogou, only: [:show, :edit, :update, :destroy]
  helper_method :account, :nextrecord
  before_action :tmp
  
  require 'savon'
  require "azure"
  
  require 'rubygems'
  require 'mongo'
  require 'zlib'
  
  
  def test
    
  end
  
  
  
  
  
  def checkreport
  
      @logger.info "checkreport sogou start"
      
      @current_not_done_report = @db[:miss_report].find({ "$and" => [{:status => 1},{:worker => @port.to_i},{:network_type => "sogou"}] })
      @db.close
      
      if @current_not_done_report.count.to_i > 0
          data = {:message => "check report sogou running", :status => "true"}
          return render :json => data, :status => :ok  
      end
    
      @not_done_report = @db[:miss_report].find({ "$and" => [{:status => 0},{:worker => @port.to_i},{:network_type => "sogou"}] }).limit(1)
      @db.close
      
      
      
      if @not_done_report.count.to_i > 0
          @not_done_report.no_cursor_timeout.each do |not_done_report_d|
            
              begin
                
              
                  @db[:miss_report].find('_id' => not_done_report_d["_id"], 'status' => 0 ).update_one('$set'=> { 'status' => 1, 'update_date' => @now })
                  @db.close
                  
                  id = not_done_report_d["network_id"]
                  report_day = not_done_report_d["report_date"]
                  
                  @logger.info "checkreport sogou running "+id.to_s+" - "+report_day.to_s
                  
                  days = @today.to_date - report_day.to_date
                  
                  url = "http://china.adeqo.com:"+@port.to_s+"/sogous/report?day="+days.to_i.to_s+"&id="+id.to_s
                  # res = Net::HTTP.get_response(URI(url))
                  
                  link = URI.parse(url)
                  http = Net::HTTP.new(link.host, link.port)
                  
                  http.read_timeout = 800
                  http.open_timeout = 800
                  res = http.start() {|http|
                    http.get(URI(url))
                  }
    
                  
                  @logger.info "checkreport running sogou report "+id.to_s+" - "+report_day.to_s
                  
                  if res.code.to_i == 200 
                          
                      @db[:miss_report].find('_id' => not_done_report_d["_id"], 'status' => 1 ).delete_one
                      @db.close
                      
                      @logger.info "checkreport done sogous report "+id.to_s+" - "+report_day.to_s
                      
                  else
                      @db[:miss_report].find('_id' => not_done_report_d["_id"], 'status' => 1 ).update_one('$set'=> { 'status' => 0, 'update_date' => @now })
                      @db.close
                      
                      data = {:message => @not_done_report, :status => "false"}
                      return render :json => data, :status => :ok
                  end
              
              rescue Exception
                  @db[:miss_report].find('_id' => not_done_report_d["_id"], 'status' => 1 ).update_one('$set'=> { 'status' => 0, 'update_date' => @now })
                  @db.close
                  
                  data = {:message => @not_done_report, :status => "false"}
                  return render :json => data, :status => :ok
              end
              # data = {:url => url, :upper_url => upper_url, :status => "true"}
              # return render :json => data, :status => :ok
          end
      end
      
      
      data = {:message => @not_done_report, :status => "true"}
      return render :json => data, :status => :ok
  
  end
  
  
  def tmp
    @tmp = "/datadrive"    
  end
    
  
  def drop
    return render :nothing => true
  end
  
  
  def sogou_api(username,password,token,api_string)            
    @sogou_api = Savon.client(
      wsdl: "http://api.agent.sogou.com:80/sem/sms/v1/"+api_string+"?wsdl",
      pretty_print_xml: true,
      log: true,
      env_namespace: :soap,
      namespaces: {"xmlns:common" => "http://api.sogou.com/sem/common/v1"},
      soap_header: { 
        "common:AuthHeader" => {
          'common:token' => token,
          'common:username' => username,
          'common:password' => password
        }
      }
    )    
  end
  
  
  
  def redownload(networkid)
    
      @redownload_network = @db[:network].find('type' => 'sogou', 'id' => networkid.to_i)
      @db.close
    
      if @redownload_network.count.to_i == 1
          
          @redownload_network.no_cursor_timeout.each do |doc|
              if doc["tmp_file"] != ""
                  unzip_folder = @tmp+"/"+doc["tmp_file"]
                  if File.directory?(unzip_folder)
                      FileUtils.remove_dir unzip_folder, true
                  end
              end
          end
          
          @db[:network].find(id: networkid.to_i).update_one('$set'=> { 'tmp_file' => "" , 'fileid' => "",'run_time' => 0, 'file_update_1' => 0, 'file_update_2' => 0, 'file_update_3' => 0, 'file_update_4' => 0, 'last_update' => @now, 'worker' => ""})  
          @db.close
      end
  end
  
  
  
  def getsogoufile(username, password, token, fileid ,network_id, tmp_file)
      
      @logger.info "getsogoufile start"
      @acc_file_path = ""
      @tmp_file = ""
      @run_csv = 0
      
      begin
          #if file_id in db, means last time the file is not ready, so reuse the id and check              
          if fileid.to_s == "" && tmp_file.to_s == "" 
            sogou_api(username,password,token,"AccountDownloadService")
            @acc_file = @sogou_api.call(:get_account_file)
            
            @header = @acc_file.header.to_hash
            @logger.info @header 
            
            @logger.info "sa1"
            
            if @header[:res_header][:desc].to_s != 'failure'
                # @return_num =  @header[:res_header][:oprs]
                # @quota =  @header[:res_header][:quota]
                
                @acc_file_body = @acc_file.body.to_hash
                @acc_file_id = @acc_file_body[:get_account_file_response][:account_file_id]
                
            else
                if @header[:res_header][:failures][:code].to_s == '30'
                    @run_csv = 2
                    @logger.info "run csv 2"
                end
                # if cant get file id, stop doing
                @db[:network].find(id: network_id.to_i).update_one('$set'=> { 'quota' => @quota.to_i })
                @db.close
            end    
                
          elsif tmp_file.to_s != ""
            @acc_file_id = tmp_file.to_s
            @run_csv = 1
          else
            @acc_file_id = fileid.to_s   
          end
          
          
            
          if @run_csv == 0 && @acc_file_id.to_s != "" 
              sogou_api(username,password,token,"AccountDownloadService")
              @acc_file_status = @sogou_api.call(:get_account_file_status, message: { accountFileId: @acc_file_id.to_s })
              @header = @acc_file_status.header.to_hash
              
              @logger.info @header
              
              if @header[:res_header][:desc].to_s != 'failure'
                
                  # @return_num =  @header[:res_header][:oprs]
                  @acc_file_status =  @acc_file_status.body.to_hash
                  @acc_file_status = @acc_file_status[:get_account_file_status_response][:is_generated]
                
                  if @acc_file_status.to_i == 1
                      # get csv path
                      @acc_file_path_r = @sogou_api.call(:get_account_file_path, message: { accountFileId: @acc_file_id.to_s })
                      
                      @header = @acc_file_path_r.header.to_hash
                      # @return_num =  @header[:res_header][:oprs]
                      
                      if @header[:res_header][:desc].to_s != 'failure'
                          @acc_file_path =  @acc_file_path_r.body.to_hash
                          @acc_file_path = @acc_file_path[:get_account_file_path_response][:account_file_path]
                          
                          @db[:network].find(id: network_id.to_i).update_one('$set'=> { 'tmp_file' => @acc_file_id.to_s, 'fileid' => ""  })
                          @db.close
                          @run_csv = 1
                      end
                  else
                      # save file id
                      @db[:network].find(id: network_id.to_i).update_one('$set'=> { 'fileid' => @acc_file_id.to_s })
                      @db.close                  
                  end
              
              end
          end
              
          @logger.info "getsogoufile done"
      rescue Exception
          @acc_file_path = ""
          @tmp_file = ""
          @run_csv = 0
          @logger.info "getsogoufile fail"
      end
  end
  
  
  def csvdetail(acc_file_id,acc_file_path, table)
            
      @logger.info "csvdetail start"      
      @unzip_name = @tmp+"/"+acc_file_id
      
      begin
          if acc_file_path.to_s != ""
              @logger.info "download file start"
              @zip_file = @tmp+"/"+acc_file_id + ".zip"
              open(@zip_file.to_s, 'wb') do |file|
                file << open(acc_file_path.to_s).read
              end
              
              @logger.info "download file done"
              
              unzip_file(@zip_file.to_s, @unzip_name.to_s)
              
              @logger.info "delete zip file start"
              File.delete(@zip_file)
              @logger.info "delete zip file done"
          end
          
          @unzip_folder = @unzip_name + "/*"
          @files = Dir.glob(@unzip_folder)
          
          @logger.info "read csv data start"
          @files.each_with_index do |file, index|
              if file.include?("account_")

app/helpers/sogous_helper.rb
module SogousHelper
end

app/views/sogous/_form.html.erb
<%= form_for(@sogou) do |f| %>
  <% if @sogou.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sogou.errors.count, "error") %> prohibited this sogou from being saved:</h2>

      <ul>
      <% @sogou.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sogous/account.html.erb
<h1>sogous account</h1>

<%=@account_info.body%>
<br />
<%=@changed_id_info.body%>

<hr />

app/views/sogous/ad.html.erb
<h1>Listing ad</h1>


<%

# concat "<hr />".html_safe  
#   
# @db[:ad_sogou].find.sort('id' => Mongo::Index::DESCENDING).each do |network|
	# concat network
	# concat "<br />".html_safe 
# end
#   
# concat "<hr />".html_safe
# 
# @ad.each_with_index do |ad, index|
	# concat ad 
	# concat "<br />".html_safe
# end
%>
 

app/views/sogous/adgroup.html.erb
sogou/adgroup


<%
# concat "<hr />".html_safe  
# 
#  
# concat "<hr />".html_safe
#  
# @db[:network].find.each do |network|
	# concat network
	# concat "<br />".html_safe 
# end
#  
# concat "<hr />".html_safe  
#   
# @db[:campaign_sogou].find.each do |network|
	# concat network
	# concat "<br />".html_safe 
# end
#    
# concat "<hr />".html_safe
# 
# @db[:adgroup_sogou].find().sort('id' => Mongo::Index::DESCENDING).each_with_index do |adgroup, index|
	# concat adgroup
	# concat "<br />".html_safe
# end
#   
# concat "<hr />".html_safe



%> 

app/views/sogous/avgposition.html.erb
avgposition


<%

# @rank.each_with_index do |rank, index|
	  # concat rank
      # if index != 0
      	  # rank_array = rank.split(",")
          # concat rank_array[2]
      # end
# end

%>

app/views/sogous/campaign.html.erb
<h1>sogous/campaign</h1>
<%
# 
# 
# concat "<hr />".html_safe  
# 
# concat @cpcplan
#  
# concat "<hr />".html_safe
#  
# @db[:network].find.each do |network|
	# concat network
	# concat "<br />".html_safe 
# end
#  
# concat "<hr />".html_safe  
#   
# @db[:campaign_sogou].find.each do |network|
	# concat network
	# concat "<br />".html_safe 
# end
#   
# concat "<hr />".html_safe

%>

app/views/sogous/edit.html.erb
<h1>Editing sogou</h1>

<%= render 'form' %>

<%= link_to 'Show', @sogou %> |
<%= link_to 'Back', sogous_path %>

app/views/sogous/index.html.erb
sogous/index

<%
# 
# concat "<hr />".html_safe  
# concat @acc_file_id
# 
# concat "<hr />".html_safe
#   
# @db[:campaign_sogou].find.sort('id' => Mongo::Index::DESCENDING).each do |network|
	# concat network
	# concat "<br />".html_safe 
# end
#   
# concat "<hr />".html_safe
# 
# 
# @db[:adgroup_sogou].find().sort('id' => Mongo::Index::DESCENDING).each_with_index do |adgroup, index|
	# concat adgroup
	# concat "<br />".html_safe
# end
#   
# concat "<hr />".html_safe
# 
# @db[:ad_sogou].find().sort('id' => Mongo::Index::DESCENDING).each_with_index do |ad, index|
	# concat ad
	# concat "<br />".html_safe
# end
#   
# concat "<hr />".html_safe
# 
# 
# concat "<hr />".html_safe
# 
# @db[:keyword_sogou].find().sort('id' => Mongo::Index::DESCENDING).each_with_index do |ad, index|
	# concat ad
	# concat "<br />".html_safe
# end
#   
# concat "<hr />".html_safe

%>

app/views/sogous/keyword.html.erb
<h1>Listing ad</h1>


<%

# concat "<hr />".html_safe  
# @index = 0;
# concat @db[:keyword_sogou].find().count.to_i
# concat "<hr />".html_safe  
# @db[:keyword_sogou].find().each do |keyword|
	# if @index.to_i == 10000
		# break
	# end
	# concat keyword
	# concat "<br />".html_safe
	# @index = @index + 1;  
# end
#   
# concat "<hr />".html_safe
# 
# @keyword.each_with_index do |ad, index|
	# concat ad
	# concat "<br />".html_safe
# end
%>
 

app/views/sogous/new.html.erb
<h1>New sogou</h1>

<%= render 'form' %>

<%= link_to 'Back', sogous_path %>

app/views/sogous/report.html.erb
report

<%

%>

app/views/sogous/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_sogou_path(@sogou) %> |
<%= link_to 'Back', sogous_path %>