config/routes.rb
Rails.application.routes.draw do
 

  get '/checktodayreport' => 'application#checktodayreport'
  get '/checklastdayreport' => 'application#checklastdayreport'
  
  
  get '/threesixties/checkreport' => 'threesixties#checkreport'
  get '/sogous/checkreport' => 'sogous#checkreport'
  get '/shenmas/checkreport' => 'shenmas#checkreport'
  get '/baidu/checkreport' => 'baidus#checkreport'

  get '/click' => 'application#click'
  get '/event' => 'application#event'

  get '/g_normal_conversion' => 'application#g_normal_conversion'

  get '/ctriprevenuereport' => 'application#ctriprevenuereport'

  get '/watchdog' => 'application#watchdog'
  get '/watchdograndom' => 'application#watchdograndom'
  get '/watchdogreset' => 'application#watchdogreset'
  get '/watchdogreport' => 'application#watchdogreport'
  
  get '/cleanwatchdogfile' => 'application#cleanwatchdogfile'
  
  

  get '/getmissingeventfile' => 'application#getmissingeventfile'
  get '/cleaneventfile' => 'application#cleaneventfile'
  get '/exporteventfile' => 'application#exporteventfile'
  get '/geteventfile' => 'application#geteventfile'
  
  get '/getmissingclickfile' => 'application#getmissingclickfile'
  get '/cleanclickfile' => 'application#cleanclickfile'
  get '/exportclickfile' => 'application#exportclickfile'
  get '/getclickfile' => 'application#getclickfile'

  get '/checktag' => 'application#checktag'

  get '/checkkeywordtag' => 'application#checkkeywordtag'
  get '/checkadtag' => 'application#checkadtag'
  
  get '/cleanlogfile' => 'application#cleanlogfile'
  get '/cleanbulkfile' => 'application#cleanbulkfile'
  get '/cleanadvancedsearchfile' => 'application#cleanadvancedsearchfile'

  post '/bulkjob' => 'application#bulkjob'
  get '/runbulkjob' => 'application#runbulkjob'
  
  
  
  get '/shenmas/test' => 'shenmas#test'
  get '/shenmas/report' => 'shenmas#report'
  
  get '/shenmas/resetreport' => 'shenmas#resetreport'
  get '/shenmas/resetnetwork' => 'shenmas#resetnetwork'
  get '/shenmas/resetdlfile' => 'shenmas#resetdlfile'
  
  get '/shenmas/avgposition' => 'shenmas#avgposition'
  
  get '/shenmas/report_tmp' => 'shenmas#report_tmp'
  
  get '/shenmas/dlaccfile' => 'shenmas#dlaccfile'
  get '/shenmas/campaign' => 'shenmas#campaign'
  get '/shenmas/adgroup' => 'shenmas#adgroup'
  get '/shenmas/ad' => 'shenmas#ad'
  get '/shenmas/keyword' => 'shenmas#keyword'
  
  get '/shenmas/apicampaign' => 'shenmas#apicampaign'
  get '/shenmas/apiadgroup' => 'shenmas#apiadgroup'
  
  get '/shenmas/updateaccount' => 'shenmas#updateaccount'
  

  get '/sogous/campaign' => 'sogous#campaign'
  get '/sogous/adgroup' => 'sogous#adgroup'
  get '/sogous/ad' => 'sogous#ad'
  get '/sogous/keyword' => 'sogous#keyword'
  
  get '/sogous/apiadgroup' => 'sogous#apiadgroup'
  get '/sogous/apicampaign' => 'sogous#apicampaign'
  
  get '/sogous/resetreport' => 'sogous#resetreport'
  get '/sogous/threemonthsreport' => 'sogous#threemonthsreport'
  get '/sogous/report' => 'sogous#report'
  get '/sogous/avgposition' => 'sogous#avgposition'
  get '/sogous/avgposition_upper' => 'sogous#avgpositionupper'
  get '/sogous/resetdlfile' => 'sogous#resetdlfile'
  get '/sogous/resetnetwork' => 'sogous#resetnetwork'
  
  get '/sogous/updateaccount' => 'sogous#updateaccount'
  get '/sogous/dlaccfile' => 'sogous#dlaccfile'
  
  
  get '/test' => 'sogous#test'
  get '/test2' => 'threesixties#test'
  get '/test3' => 'baidus#test'
  get '/test4' => 'shenmas#test'

  
  get '/threesixties/campaign' => 'threesixties#campaign'
  get '/threesixties/adgroup' => 'threesixties#adgroup'
  get '/threesixties/ad' => 'threesixties#ad'
  get '/threesixties/keyword' => 'threesixties#keyword'
  
  get '/threesixties/campaignandadgroup' => 'threesixties#campaignandadgroup'
  get '/threesixties/adandkeyword' => 'threesixties#adandkeyword'
  
  get '/threesixties/apicampaign' => 'threesixties#apicampaign'
  get '/threesixties/apiadgroup' => 'threesixties#apiadgroup'
  
  get '/threesixties/resetreport' => 'threesixties#resetreport'
  get '/threesixties/threemonthsreport' => 'threesixties#threemonthsreport'
  get '/threesixties/report' => 'threesixties#report'
  get '/threesixties/report_upper' => 'threesixties#report_upper'
  get '/threesixties/resetdlfile' => 'threesixties#resetdlfile'
  get '/threesixties/resetnetwork' => 'threesixties#resetnetwork'
  
  get '/threesixties/updateaccount' => 'threesixties#updateaccount'
  get '/threesixties/dlaccfile' => 'threesixties#dlaccfile'
  
  get '/threemonthsevent' => 'application#threemonthsevent'
  get '/threemonthsclicks' => 'application#threemonthsclicks'
  get '/g_conversion' => 'application#g_conversion'
  get '/g_revenue' => 'application#g_revenue'
  
  get '/advancedsearchjob' => 'application#advancedsearchjob'
  get '/checkquote' => 'application#checkquote'
  
  
  get '/baidu/apicampaign' => 'baidus#apicampaign'
  get '/baidu/apiadgroup' => 'baidus#apiadgroup'
  
  get '/baidu/resetreport' => 'baidus#resetreport'
  get '/baidu/report' => 'baidus#report'
  get '/baidu/avgposition' => 'baidus#avgposition'
  
  
  
  get '/baidu/dlaccfile' => 'baidus#dlaccfile'
  
  get '/baidu/updateaccount' => 'baidus#updateaccount'
  
  get '/baidu/campaign' => 'baidus#campaign'
  get '/baidu/adgroup' => 'baidus#adgroup'
  get '/baidu/ad' => 'baidus#ad'
  get '/baidu/keyword' => 'baidus#keyword'
  
  get '/baidu/resetdlfile' => 'baidus#resetdlfile'
  get '/baidu/resetnetwork' => 'baidus#resetnetwork'
  
  
  resources :sogous
  resources :threesixties
  resources :baidus
  resources :shenmas

  get '*unmatched_route' => 'application#not_found'
  

  

end

app/models/threesixty.rb
class Threesixty < ActiveRecord::Base
end

app/controllers/threesixties_controller.rb
class ThreesixtiesController < ApplicationController
  before_action :set_threesixty, only: [:show, :edit, :update, :destroy]
  before_action :tmp
  
  require 'rubygems'
  require 'httparty'
  
  require 'mongo'
  require 'zlib'
  
  def test
        # mg_client = Mailgun::Client.new("key-63ad3b57013d96ecf8b581b02c917dbe")  
        # mb_obj = Mailgun::MessageBuilder.new()
#      
        # mb_obj.set_from_address("do-not-reply@adeqo.com", {"first"=>"Adeqo", "last" => ""});
        # mb_obj.add_recipient(:to, "jkwan@bmgww.com", {"first" => "", "last" => ""});
#         
        # mb_obj.set_subject("Adeqo | test");  
        # # mb_obj.set_text_body(result_msg);
#         
        # result_msg = "<p>test</p>"
        # result_msg = result_msg + "<p>Please login and visit the account page:<br /><a href='http://china.adeqo.com/account'>http://china.adeqo.com/account</a></p>"
        # result_msg = result_msg + "<p>to update Password and API Token Information</p>"
        # result_msg = result_msg + "<p>Incorrect API credentials will stop us from keeping the information up-to-date. The users will not be able to use any editing functions.</p>"
        # result_msg = result_msg + "<br /><p>Team BMG</p>" 
        # mb_obj.set_html_body(result_msg);
        # mail = mg_client.send_message("china.adeqo.com", mb_obj)
  end
  
  def tmp
    @tmp = "/datadrive"    
  end
  
  def checkreport
    
      @logger.info "checkreport 360 start"
      
      @current_not_done_report = @db[:miss_report].find({ "$and" => [{:status => 1},{:worker => @port.to_i},{:network_type => "360"}] })
      @db.close
      
      if @current_not_done_report.count.to_i > 0
          data = {:message => "check report 360 running", :status => "true"}
          return render :json => data, :status => :ok  
      end
    
      @not_done_report = @db[:miss_report].find({ "$and" => [{:status => 0},{:worker => @port.to_i},{:network_type => "360"}] }).limit(1)
      @db.close
      
      # ?day=3
      
      
      if @not_done_report.count.to_i > 0
          @not_done_report.no_cursor_timeout.each do |not_done_report_d|
            
              begin
                  @db[:miss_report].find('_id' => not_done_report_d["_id"], 'status' => 0 ).update_one('$set'=> { 'status' => 1, 'update_date' => @now})
                  @db.close
                  
                  id = not_done_report_d["network_id"]
                  report_day = not_done_report_d["report_date"]
                  
                  @logger.info "checkreport 360 running "+id.to_s+" - "+report_day.to_s
                  
                  days = @today.to_date - report_day.to_date
                  
                  url = "http://china.adeqo.com:"+@port.to_s+"/threesixties/report?day="+days.to_i.to_s+"&id="+id.to_s
                  # res = Net::HTTP.get_response(URI(url))
                  
                  link = URI.parse(url)
                  http = Net::HTTP.new(link.host, link.port)
                  
                  http.read_timeout = 900
                  http.open_timeout = 900
                  res = http.start() {|http|
                    http.get(URI(url))
                  }
    
                  
                  @logger.info "checkreport running 360 report "+id.to_s+" - "+report_day.to_s
                  
                  if res.code.to_i == 200 
                      url = "http://china.adeqo.com:"+@port.to_s+"/threesixties/report_upper?day="+days.to_i.to_s+"&id="+id.to_s
                      # res = Net::HTTP.get_response(URI(upper_url))
                      
                      link = URI.parse(url)
                      http = Net::HTTP.new(link.host, link.port)
                      
                      http.read_timeout = 900
                      http.open_timeout = 900
                      res = http.start() {|http|
                        http.get(URI(url))
                      }
                      
                      @logger.info "checkreport running 360 report upper"+id.to_s+" - "+report_day.to_s
                      
                      if res.code.to_i == 200
                          
                          @db[:miss_report].find('_id' => not_done_report_d["_id"], 'status' => 1 ).delete_one
                          @db.close
                          
                          @logger.info "checkreport done 360 report "+id.to_s+" - "+report_day.to_s
                      else
                          @db[:miss_report].find('_id' => not_done_report_d["_id"], 'status' => 1 ).update_one('$set'=> { 'status' => 0, 'update_date' => @now })
                          @db.close
                          
                          data = {:message => @not_done_report, :status => "false"}
                          return render :json => data, :status => :ok
                      end
                  else
                      @db[:miss_report].find('_id' => not_done_report_d["_id"], 'status' => 1 ).update_one('$set'=> { 'status' => 0, 'update_date' => @now })
                      @db.close
                      
                      data = {:message => @not_done_report, :status => "false"}
                      return render :json => data, :status => :ok
                  end
              
              
              rescue Exception
                  @db[:miss_report].find('_id' => not_done_report_d["_id"], 'status' => 1 ).update_one('$set'=> { 'status' => 0, 'update_date' => @now })
                  @db.close
                  
                  data = {:message => @not_done_report, :status => "false"}
                  return render :json => data, :status => :ok
              end
              # data = {:url => url, :upper_url => upper_url, :status => "true"}
              # return render :json => data, :status => :ok
          end
      end
      
      
      data = {:message => @not_done_report, :status => "true"}
      return render :json => data, :status => :ok
      
  end
  
   
  def apiadgroup
      @logger.info "360 api adgroup start"
      
      @campaign_id = params[:id]
    
      if @campaign_id.nil?
          @current_campaign = @db[:all_campaign].find({ "$and" => [{:network_type => '360'}, {:api_worker => @port.to_i}, {:api_update => 4}] })
          @db.close
          
          if @current_campaign.count.to_i >= 1
              @logger.info "working, no need update campaign api adgroup"
              return render :nothing => true
          end
          
          @campaign = @db[:all_campaign].find({ "$and" => [{:network_type => '360'}, {:api_worker => @port.to_i}, {:api_update => 3}] }).sort({ last_update: -1 }).limit(1)
          @db.close
          
          if @campaign.count.to_i == 0
              @logger.info "no need update campaign api adgroup"
              return render :nothing => true
          end
          
      else
          @campaign = @db[:all_campaign].find({ "$and" => [{:campaign_id => @campaign_id.to_i}, {:network_type => '360'}] })
          @db.close
      end
      
      
      if @campaign.count.to_i
          
          @campaign.no_cursor_timeout.each do |campaign|
              @network_id = campaign["network_id"].to_i
              @campaign_id = campaign["campaign_id"].to_i
              @campaign_name = campaign["campaign_name"].to_s
          end
          
          @network = @db[:network].find({ "$and" => [{:id => @network_id.to_i}, {:type => '360'}] })
          @db.close
          
          if @network.count.to_i > 0
              @network.no_cursor_timeout.each do |network_d|
                  @tracking_type = network_d["tracking_type"].to_s
                  @ad_redirect = network_d["ad_redirect"].to_s
                  @keyword_redirect = network_d["keyword_redirect"].to_s
                  @company_id = network_d["company_id"].to_s
                  @cookie_length = network_d["cookie_length"].to_s
                  
                  @account_id = network_d["accountid"].to_i
                  @account_name = network_d["name"].to_s
                
                  @username = network_d["username"]
                  @password = network_d["password"]
                  @apitoken = network_d["api_token"]
                  @apisecret = network_d["api_secret"]
                  
                  login_info = threesixty_api_login(@username,@password,@apitoken,@apisecret)
                  @refresh_token = login_info["account_clientLogin_response"]["accessToken"]
                  
                  if !@refresh_token.nil?
                      @update_res = threesixty_api( @apitoken.to_s, @refresh_token, "account", "getInfo")
                      @remain_quote = @response.headers["quotaremain"].to_i
                      
                      if @remain_quote.to_i >= 500
                          db_name = "adgroup_360_"+@network_id.to_s
                          
                          @adgroup = @threesixty_db[db_name].find({ "$and" => [{:campaign_id => @campaign_id.to_i}, {:api_update_ad => 1}, {:api_update_keyword => 1}, {:api_worker => @port.to_i}] })
                          @threesixty_db.close()
                          
                          @adgroup_id_array = []
                          @adgroup_arr = []
                          
                          if @adgroup.count.to_i
                        
                              @adgroup.no_cursor_timeout.each do |adgroup_d|
                                  @adgroup_id_array << adgroup_d["adgroup_id"].to_i
                              end
                              
                              @adgroup_id_array_str = @adgroup_id_array.join(",")
                              body = {}
                              body[:idList] = "["+@adgroup_id_array_str.to_s+"]"
                              
                              @update_res = threesixty_api( @apitoken.to_s, @refresh_token, "group", "getInfoByIdList", body)
                              

app/helpers/threesixties_helper.rb
module ThreesixtiesHelper
end

app/views/threesixties/_form.html.erb
<%= form_for(@threesixty) do |f| %>
  <% if @threesixty.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@threesixty.errors.count, "error") %> prohibited this threesixty from being saved:</h2>

      <ul>
      <% @threesixty.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/threesixties/edit.html.erb
<h1>Editing threesixty</h1>

<%= render 'form' %>

<%= link_to 'Show', @threesixty %> |
<%= link_to 'Back', threesixties_path %>

app/views/threesixties/index.html.erb
<h1>360 camp</h1>

<%=@file%>

<%
# CSV.foreach(@file, :encoding => 'GB18030').each_with_index do |csv, index|	
# # 	
	# if index.to_i < 1 
# # 		
		# concat csv
# 		
#  		
#  		
		# if csv[9].nil? && csv[11].nil? && csv[13].nil? && csv[16].nil? && csv[20].nil? && csv[22].nil?
			# concat "campaign"
# 			
			# @db[:campaign_360].insert_one({ 
	                                        # network_id: doc["id"].to_i, 
	                                        # account_id: csv[1].to_i,
	                                        # account_name: csv[2].to_i,
	                                        # campaign_id: csv[0].to_i,
	                                        # campaign_name: csv[3].to_s, 
	                                        # budget: csv[4].to_f, 
	                                        # regions: csv[26].to_s, 
	                                        # schedule: csv[27].to_s,
	                                        # start_date: csv[2].to_s,
	                                        # end_date: csv[29].to_s,
	                                        # status: csv[6].to_s,
	                                        # sys_status: csv[7].to_s,
	                                        # extend_ad_type: csv[66].to_i,
	                                        # mobile_price_rate: csv[70].to_f,
	                                        # update_date: csv[31],                                            
	                                        # create_date: csv[30] 
                                        # })
# 			
# 			
		# end
#  		
#  		
		# if !csv[9].nil? && !csv[11].nil? && csv[13].nil? && csv[16].nil? && csv[20].nil? && csv[22].nil?
			# concat "adgroup"
# 			
# 			
			# @db[:adgroup_360].insert_one({ 
                                          # network_id: doc["id"].to_i,
                                          # account_id: csv[1].to_i,
                                          # account_name: csv[2].to_s,
                                          # campaign_id: @campaign_id.to_i,
                                          # campaign_name: csv[3].to_s,
                                          # adgroup_id: csv[0].to_i,
                                          # adgroup_name: csv[9].to_s,
                                          # price: csv[10].to_f,
                                          # negative_words: csv[19].to_s,
                                          # status: csv[11].to_s,
                                          # sys_status: csv[12].to_s,
                                          # update_date: csv[31],                                            
                                          # create_date: csv[30] 
                                          # })
# 			
		# end
#  		
#  		
#  		
		# if !csv[20].nil? && csv[13].nil? && csv[16].nil?
			# concat "ad"
# 			
# 			
			# @db[:ad_360].insert_one({ 
                                          # network_id: doc["id"].to_i,
                                          # account_id: csv[1].to_i,
                                          # account_name: csv[2].to_s,
                                          # campaign_id: @campaign_id.to_i,
                                          # campaign_name: csv[3].to_s,
                                          # adgroup_id: @adgroup_id.to_i,
                                          # ad_id: csv[0].to_i,
                                          # title: csv[20].to_s, 
                                          # description: csv[21].to_s, 
                                          # status: csv[22].to_s,
                                          # sys_status: csv[23].to_s,
                                          # show_url: csv[24].to_s,
                                          # visit_url: csv[25].to_s,
                                          # mobile_show_url: csv[68].to_s,
                                          # mobile_visit_url: csv[69].to_s,
                                          # extend_ad_type: csv[66].to_i,
                                          # update_date: csv[31],                                            
                                          # create_date: csv[30] 
                                          # })
# 			
#  			
		# end
#  		
#  		
#  		
		# if !csv[13].nil? && csv[20].nil? && csv[22].nil?
			# concat "keyword"
#  			
 			# @db[:keyword_360].insert_one({ 
                                        # network_id: doc["id"].to_i,
                                        # account_id: csv[1].to_i,
                                        # account_name: csv[2].to_i,
                                        # campaign_id: @campaign_id.to_i,
                                        # campaign_name: csv[3].to_s,
                                        # adgroup_id: @adgroup_id.to_i,
                                        # keyword_id: csv[0].to_i,
                                        # keyword: csv[13].to_s,
                                        # price: csv[15].to_f, 
                                        # status: csv[16].to_s,
                                        # sys_status: csv[17].to_s,
                                        # match_type: csv[14].to_i,
                                        # visit_url: csv[25].to_s,
                                        # mobile_visit_url: csv[67].to_s,
                                        # cpc_quality: csv[32].to_f,
                                        # extend_ad_type: csv[66].to_i,
                                        # update_date: csv[31],                                            
                                        # create_date: csv[30] 
                                        # })
#  			
		# end
# 		
		# concat "<hr>".html_safe
# 		
	# else
		# break	
	# end
# end
%>
 

app/views/threesixties/new.html.erb
<h1>New threesixty</h1>

<%= render 'form' %>

<%= link_to 'Back', threesixties_path %>

app/views/threesixties/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_threesixty_path(@threesixty) %> |
<%= link_to 'Back', threesixties_path %>